[package]
name = "pwsp"
version = "0.1.31"
edition = "2024"
authors = ["arabian"]
description = "A simple soundpad application written in Rust using egui for the GUI, pipewire for audio input/output, and rodio for audio decoding."
readme = "README.md"
homepage = "https://github.com/arabianq/pipewire-soundpad"
repository = "https://github.com/arabianq/pipewire-soundpad"
license = "MIT"
keywords = ["soundpad", "pipewire"]


[dependencies]
egui = "0.32.0"
eframe = "0.32.0"
egui_material_icons = "0.4.0"
rfd = "0.15.3"
dirs = "6.0.0"
rodio = { version = "0.20.1", default-features = false, features = ["symphonia-all"] }
metadata = "0.1.10"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"

[package.metadata.deb]
assets = [
    { source = "target/release/pwsp", dest = "usr/bin/", mode = "755" },
    { source = "pwsp.desktop", dest = "usr/share/applications/pwsp.desktop", mode = "644" },
]
depends = "libX11"

[package.metadata.generate-rpm]
assets = [
    { source = "target/x86_64-unknown-linux-gnu/release/pwsp", dest = "/usr/bin/pwsp", mode = "755" },
    { source = "pwsp.desktop", dest = "/usr/share/applications/pwsp.desktop", mode = "644" }
]