[package]
name = "pwsp"
version = "1.0.0"
edition = "2024"
authors = ["arabian"]
description = "A simple soundpad application written in Rust using egui for the GUI, pipewire for audio input/output, and rodio for audio decoding."
readme = "README.md"
homepage = "https://github.com/arabianq/pipewire-soundpad"
repository = "https://github.com/arabianq/pipewire-soundpad"
license = "MIT"
keywords = ["soundpad", "pipewire"]


[dependencies]

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"
