# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           pwsp
Version:        1.0.0
Release:        %autorelease
Summary:        Lets you play audio files through your microphone

SourceLicense:  MIT
License:        MIT

URL:            https://github.com/arabianq/pipewire-soundpad
Source:         https://github.com/arabianq/pipewire-soundpad/archive/refs/tags/%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
PWSP lets you play audio files through your microphone. Has both CLI and
GUI clients.}

%description %{_description}

%prep
%autosetup -n pwsp-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/pwsp-cli
%{_bindir}/pwsp-daemon
%{_bindir}/pwsp-gui

%changelog
%autochangelog
